POST http://localhost:7071/api/GetTopReputableByLocation HTTP/3.0
content-type: application/json

{
    "top":5,
    "contains":"Western Cape"
}

###
POST http://localhost:7071/api/GetTopReputableByLocation HTTP/3.0
content-type: application/json

{
    "top":10,
    "startsWith":"Cape Town"
}

###
POST http://localhost:7071/api/GetTopReputableByLocation HTTP/3.0
content-type: application/json

{
    "top":15,
    "endsWith":"South Africa"
}

###
POST http://localhost:7071/api/GetTopReputableByLocation HTTP/3.0
content-type: application/json

{
    "contains":"Africa"
}

###
POST http://localhost:7071/api/GetTopReputableByLocation HTTP/3.0
content-type: application/json

{}

###